# ??????
server:
  # ????HTTP??????8080
  port: 8080
  servlet:
    # ???????
    context-path: /
  # undertow ??
  undertow:
    # HTTP post???????????-1????????????
    max-http-post-size: -1
    # ????????buffer,??buffer?????????IO??,????netty???????
    # ??buffer?????,???????????
    buffer-size: 512
    # ?????????
    direct-buffers: true
    threads:
      # ??IO???, ???????????,?????????, ??????CPU??????
      io: 8
      # ???????, ?????servlet??????, undertow????????????,?????????????
      worker: 256

